language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g codecov
  - yarn

jobs:
  include:
    - stage: Run Tests
      script:
        - yarn run test
        - codecov
    - stage: Run Semantic Release
      script:
        - npx semantic-release
